const SAVE = 'SAVE';
const STARTLOADING = 'STARTLOADING';
const STOPLOADING = 'STOPLOADING';
const SELECTINDEX = 'SELECTINDEX';


export default {
  SAVE,
  STARTLOADING,
  STOPLOADING,
  SELECTINDEX,
}